package com.brunoferre.gestioninventario.vista;

import java.awt.Dimension;
import java.awt.DisplayMode;
import java.awt.GraphicsConfiguration;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.awt.Toolkit;
import javax.swing.SwingWorker;

/**
 *
 * @author bruno
 */
public class FrmOpciones extends javax.swing.JFrame {

    FrmProductos frmProductos = null;
    FrmVentas frmVentas = null;
    FrmProductosFaltantes faltantes = null;
    FrmHistorial historial = null;

    Loader loader = new Loader();

    public FrmOpciones() {
        initComponents();
        // Obtener el tamaño de la pantalla y posicionar en la izquierda
        // Obtener la pantalla principal
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice[] screens = ge.getScreenDevices(); // Obtiene la pantalla principal
        Rectangle bounds;
        if (screens.length > 1) {
            bounds = screens[1].getDefaultConfiguration().getBounds();

        } else {
            // Si solo hay una pantalla, usar la principal
            bounds = screens[0].getDefaultConfiguration().getBounds();
        }
        // Definir margen a la izquierda
        int margenIzquierda = 20;
        // Posicionar en la izquierda y centrar verticalmente
        int x = bounds.x + margenIzquierda; // A la izquierda de la pantalla seleccionada
        int y = bounds.y + (bounds.height - this.getHeight()) / 2;
        this.setLocation(x, y);
        this.setResizable(false);
        this.setEnabled(true);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnVenta = new javax.swing.JButton();
        btnFaltantes = new javax.swing.JButton();
        btnGestionPr = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        btnBuscarVenta = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ACCESOS RAPIDOS");
        setEnabled(false);
        setUndecorated(true);

        jButton1.setBackground(new java.awt.Color(0, 109, 208));
        jButton1.setFont(new java.awt.Font("Ubuntu Mono", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("MI CUENTA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnVenta.setBackground(new java.awt.Color(0, 109, 208));
        btnVenta.setFont(new java.awt.Font("Ubuntu Mono", 1, 12)); // NOI18N
        btnVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnVenta.setText("GESTION VENTAS");
        btnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaActionPerformed(evt);
            }
        });

        btnFaltantes.setBackground(new java.awt.Color(0, 109, 208));
        btnFaltantes.setFont(new java.awt.Font("Ubuntu Mono", 1, 12)); // NOI18N
        btnFaltantes.setForeground(new java.awt.Color(255, 255, 255));
        btnFaltantes.setText("PRODUCTOS FALTANTES");
        btnFaltantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFaltantesActionPerformed(evt);
            }
        });

        btnGestionPr.setBackground(new java.awt.Color(0, 109, 208));
        btnGestionPr.setFont(new java.awt.Font("Ubuntu Mono", 1, 12)); // NOI18N
        btnGestionPr.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionPr.setText("GESTION DE PRODUCTOS");
        btnGestionPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionPrActionPerformed(evt);
            }
        });

        btnHistorial.setBackground(new java.awt.Color(0, 109, 208));
        btnHistorial.setFont(new java.awt.Font("Ubuntu Mono", 1, 12)); // NOI18N
        btnHistorial.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorial.setText("HISTORIAL DE VENTAS");
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });

        btnBuscarVenta.setBackground(new java.awt.Color(0, 109, 208));
        btnBuscarVenta.setFont(new java.awt.Font("Ubuntu Mono", 1, 12)); // NOI18N
        btnBuscarVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarVenta.setText("BUSCAR VENTA");
        btnBuscarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVentaActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(0, 109, 208));
        btnSalir.setFont(new java.awt.Font("Ubuntu Mono", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("CERRAR SISTEMA");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionPr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFaltantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnGestionPr, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnFaltantes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnBuscarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed
        // TODO add your handling code here:
        loader.setVisible(true);
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                // Aquí iría el código para realizar la consulta a la base de datos
                frmVentas = new FrmVentas();
                // Simulamos la consulta con un retraso de 3 segundos (puedes reemplazar esto con tu consulta real)
                return null;
            }

            @Override
            protected void done() {
                // Cerrar el loader y abrir la ventana de productos
                loader.dispose();
                frmVentas.setVisible(true);
            }
        };

        // Iniciar el trabajador en segundo plano
        worker.execute();
    }//GEN-LAST:event_btnVentaActionPerformed

    private void btnGestionPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionPrActionPerformed
        // TODO add your handling code here:

        loader.setVisible(true);
        // Crear un SwingWorker para realizar la consulta en segundo plano
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                // Aquí iría el código para realizar la consulta a la base de datos
                frmProductos = new FrmProductos();
                // Simulamos la consulta con un retraso de 3 segundos (puedes reemplazar esto con tu consulta real)
                return null;
            }

            @Override
            protected void done() {
                // Cerrar el loader y abrir la ventana de productos
                loader.dispose();
                frmProductos.setVisible(true);
            }
        };

        // Iniciar el trabajador en segundo plano
        worker.execute();
    }//GEN-LAST:event_btnGestionPrActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MiCuenta cuenta = new MiCuenta();
        cuenta.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnFaltantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFaltantesActionPerformed
        // TODO add your handling code here:
        loader.setVisible(true);
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                // Aquí iría el código para realizar la consulta a la base de datos
                faltantes = new FrmProductosFaltantes();
                // Simulamos la consulta con un retraso de 3 segundos (puedes reemplazar esto con tu consulta real)
                return null;
            }

            @Override
            protected void done() {
                // Cerrar el loader y abrir la ventana de productos
                loader.dispose();
                faltantes.setVisible(true);
            }
        };

        // Iniciar el trabajador en segundo plano
        worker.execute();
    }//GEN-LAST:event_btnFaltantesActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        // TODO add your handling code here:
        loader.setVisible(true);
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                // Aquí iría el código para realizar la consulta a la base de datos
                historial = new FrmHistorial();
                // Simulamos la consulta con un retraso de 3 segundos (puedes reemplazar esto con tu consulta real)
                return null;
            }

            @Override
            protected void done() {
                // Cerrar el loader y abrir la ventana de productos
                loader.dispose();
                historial.setVisible(true);
            }
        };

        // Iniciar el trabajador en segundo plano
        worker.execute();
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnBuscarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVentaActionPerformed
        // TODO add your handling code here:
        FrmBuscarVenta frmBuscarVenta = new FrmBuscarVenta();
        frmBuscarVenta.setVisible(true);
    }//GEN-LAST:event_btnBuscarVentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarVenta;
    private javax.swing.JButton btnFaltantes;
    private javax.swing.JButton btnGestionPr;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVenta;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
